### ISSUE TITLE
OS Version Compatibility

### ISSUE THREAD

**Issue by Gitoffthelawn** [JocysCom/FocusLogger#5]
With which versions of Windows is this tool compatible?

I can add the info to the README for you if it is provided.

**Comment by EJocys** [comment]
@Gitoffthelawn 

Released new version and added requirements on main page:

# System Requirements

- Microsoft Windows 7 SP1 or newer.

  https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md
- Microsoft .NET 6.0 (included with Windows Updates).

  https://dotnet.microsoft.com/en-us/download/dotnet

**Comment by Gitoffthelawn** [comment]
Thanks!  Out of curiosity, what's holding it back from working with .NET 4.7?

**Comment by EJocys** [comment]
@Gitoffthelawn:
Probably lack of time forces me to keep it as simple as possible and use only one executable per application. This means that I have to choose between ".NET Framework" and ".NET Core" build. Choosing ".NET Core" seemed like a simple choice because Microsoft stopped all new development on .NET Framework 4.x 4 years ago and moved to .NET 6.0 which is free, open source and has better cross-platform compatibility which works with Windows, Mac OS X and Linux.

I still have a lot of apps written on .NET Framework 4.x and slowly upgrading them to .NET Core.

**Comment by Gitoffthelawn** [comment]
Thanks for the details.  Makes sense.

Personally, I prefer .NET 4.x when .NET Core isn't needed because it will work with **offline** (not connected to any networks) Win7 systems that won't receive MS updates.   IIRC, .NET 4.x is included in the official MS Win7 SP1 ISO's.

Many standalone lab computers run independently, and aren't networked (and thus don't have internet access).

As you mentioned, the cross-platform compatibility of .NET Core with Linux and macOS are a big plus, when needed..
